apiVersion: v2
name: wandb
description: A Helm chart for deploying W&B to Kubernetes
type: application
version: 0.3.9
appVersion: 0.60.0
icon: https://wandb.ai/logo.svg
maintainers:
  - name: wandb
    email: support@wandb.com
    url: https://wandb.com
dependencies:
  - name: wandb-base
    alias: console
    version: "0.11.6"
    repository: file://charts/wandb-base
    condition: console.install
  - name: wandb-base
    alias: weave
    version: "0.11.6"
    repository: file://charts/wandb-base
    condition: weave.install
    - name: wandb-base
    alias: parquet
    version: "0.11.6"
    repository: file://charts/wandb-base
    condition: parquet.install
  - name: mysql
    version: "*.*.*"
    repository: file://charts/mysql
    condition: mysql.install
  - name: prometheus
    version: "*.*.*"
    repository: file://charts/prometheus
    condition: prometheus.install
  - name: redis
    version: "18.*.*"
    repository: file://charts/redis
    condition: redis.install