apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wandb-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/bodgity/wandb.git"
    targetRevision: "official"
    path: "charts/wandb"
    helm:
      releaseName: wandb
      values: |
        global:
          host: "wandb.joshuasross.com"
          bucket:
            name: "wandb-artifacts-prod-joshross"
            region: "eu-west-1"
          mysql:
          host: wandb-mysql.choe02qeeova.eu-west-1.rds.amazonaws.com
          port: 3306
          database: wandb
          user: wandb
          passwordSecret:
            name: wandb-db
            passwordKey: password
          license: eyJhbGciOiJSUzI1NiIsImtpZCI6InUzaHgyQjQyQWhEUXM1M0xQY09yNnZhaTdoSlduYnF1bTRZTlZWd1VwSWM9In0.eyJjb25jdXJyZW50QWdlbnRzIjoxMCwidHJpYWwiOnRydWUsIm1heFN0b3JhZ2VHYiI6MTAwMDAwMCwibWF4VGVhbXMiOjUwLCJtYXhVc2VycyI6MTAwLCJtYXhWaWV3T25seVVzZXJzIjowLCJtYXhSZWdpc3RlcmVkTW9kZWxzIjo1LCJleHBpcmVzQXQiOiIyMDI2LTAxLTI3VDIyOjMzOjA2LjI4NFoiLCJkZXBsb3ltZW50SWQiOiI1ZWNjYjZkZC1jNDY2LTQxZmUtOGEzZC05YWQ2MzcyOWQ1MmIiLCJmbGFncyI6WyJOT1RJRklDQVRJT05TIiwic2xhY2siLCJub3RpZmljYXRpb25zIiwiU0NBTEFCTEUiLCJteXNxbCIsInMzIiwicmVkaXMiLCJNQU5BR0VNRU5UIiwib3JnX2Rhc2giLCJhdXRoMCIsImNvbGxlY3RfYXVkaXRfbG9ncyIsInJiYWMiXSwiY29udHJhY3RTdGFydERhdGUiOiIyMDI1LTEyLTI4VDIyOjMzOjA2LjI4NFoiLCJhY2Nlc3NLZXkiOiJjZDM4YWFmOS0zMWUxLTQ5NzItODQyYi00ZTJjN2Y0ZmFmMTIiLCJzZWF0cyI6MTAwLCJ2aWV3T25seVNlYXRzIjowLCJ0ZWFtcyI6NTAsInJlZ2lzdGVyZWRNb2RlbHMiOjUsInN0b3JhZ2VHaWdzIjoxMDAwMDAwLCJleHAiOjE3Njk1NTMxODYsIndlYXZlTGltaXRzIjp7IndlYXZlTGltaXRCeXRlcyI6bnVsbCwid2VhdmVPdmVyYWdlQ29zdENlbnRzIjowLCJ3ZWF2ZU92ZXJhZ2VVbml0IjoiTUIifX0.cCJHm00u7hs_kP4NoDERV_U06Zpe1FefsoYXuGrmFEZoHXSbFlizwWAiBFCPuvC60lvfgb5HVUjzH_ICR62UhrZ7AbV55gJI_ficS7JpQd5srIgqQj-cDWHoFq7fqOYHW0JAJ5WxUmR5b5Z7fKeoisq64lsIfqhutmOcbZy6z9qoOtrarMdfxOu_ZdjnjJ0ScbpA2Shxl7kq-NnaTin2BoWGG7SHviPOHsgsig89inuxTDom8YhrRsjeVGru5frlc45lUwg_ZZ1roGCwpMT3uZOAYPFzke1GgccQ8HYQcUBFt7fqIiXbdEyYuQZCnXgADaokU2hTL8x6hYX9syY1IQ
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: wandb-cr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
